### ISSUE TITLE
(Point, MaybeScalar) from serialized bytes.

### ISSUE THREAD

**Issue by samrock5000** [conduition/secp#1]
I was able to verify a schnorr signature in a js library after serializing  the sig tuple:

```rust
        signature
            .0
            .serialize_xonly()
            .iter()
            .cloned()
            .chain(signature.1.serialize().iter().cloned())
            .collect::<Vec<_>>()
```
    
    
just wondering how I can get back the the tuple (Point, MaybeScalar) from a [u8; 64] sig.

**Comment by conduition** [comment]
You may find [my other crate, `musig2`](https://docs.rs/musig2/latest/musig2/) useful. It uses `secp` under the hood to provide BIP340 schnorr signature utilities including single-signatures, adaptor sigs, and $n$-of-$n$ multisig. Particularly check out these methods on `CompactSignature`:

- https://docs.rs/musig2/latest/musig2/struct.CompactSignature.html#method.from_bytes
- https://docs.rs/musig2/latest/musig2/struct.CompactSignature.html#method.serialize

But if you'd like to use `secp` to do that manually, you can use [`Point::lift_x`](https://docs.rs/secp/latest/secp/struct.Point.html#method.lift_x) to parse the signature nonce point $R$, and [`MaybeScalar::from_slice`](https://docs.rs/secp/latest/secp/enum.MaybeScalar.html#method.from_slice) to parse the signature scalar $s$.

**Comment by samrock5000** [comment]
Nice,I was actually using rfc6979 to generate k for this older variant of the BIP340 schnorr signature;

```
/**
 * Custom Schnorr-based signature scheme.
 *
 * Signing:
 *   Inputs:
 *     32-byte message m,
 *     32-byte scalar key x (!=0)
 *     public key point P,
 *     32-byte scalar nonce k (!=0)
 *
 *   Compute point R = k * G. Negate nonce if R.y is not a quadratic residue.
 *   Compute scalar e = Hash(R.x || compressed(P) || m) mod n.
 *   Compute scalar s = k + e * x.
 *   The signature is (R.x, s).
 */
```
I just cant find a way to check  if "R.y is not a quadratic residue".
